package com.maoyan.model;

import java.util.Date;

public class TestBlog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_blog.id
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_blog.author
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    private Long author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_blog.blog_content
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    private String blogContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_blog.create_time
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_blog.update_time
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_blog.id
     *
     * @return the value of test_blog.id
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_blog.id
     *
     * @param id the value for test_blog.id
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_blog.author
     *
     * @return the value of test_blog.author
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    public Long getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_blog.author
     *
     * @param author the value for test_blog.author
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    public void setAuthor(Long author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_blog.blog_content
     *
     * @return the value of test_blog.blog_content
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    public String getBlogContent() {
        return blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_blog.blog_content
     *
     * @param blogContent the value for test_blog.blog_content
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_blog.create_time
     *
     * @return the value of test_blog.create_time
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_blog.create_time
     *
     * @param createTime the value for test_blog.create_time
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_blog.update_time
     *
     * @return the value of test_blog.update_time
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_blog.update_time
     *
     * @param updateTime the value for test_blog.update_time
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}