package com.maoyan.mapper;

import com.maoyan.model.TestBlog;
import com.maoyan.model.TestBlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestBlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_blog
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    long countByExample(TestBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_blog
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int deleteByExample(TestBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_blog
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_blog
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int insert(TestBlog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_blog
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int insertSelective(TestBlog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_blog
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    List<TestBlog> selectByExample(TestBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_blog
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    TestBlog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_blog
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int updateByExampleSelective(@Param("row") TestBlog row, @Param("example") TestBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_blog
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int updateByExample(@Param("row") TestBlog row, @Param("example") TestBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_blog
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int updateByPrimaryKeySelective(TestBlog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_blog
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int updateByPrimaryKey(TestBlog row);
}