package com.maoyan.mapper;

import com.maoyan.model.TestUser;
import com.maoyan.model.TestUserExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TestUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    long countByExample(TestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int deleteByExample(TestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int insert(TestUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int insertSelective(TestUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    List<TestUser> selectByExample(TestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    TestUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int updateByExampleSelective(@Param("row") TestUser row, @Param("example") TestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int updateByExample(@Param("row") TestUser row, @Param("example") TestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int updateByPrimaryKeySelective(TestUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated Mon May 06 21:25:25 CST 2024
     */
    int updateByPrimaryKey(TestUser row);
}